package com.bionote.record;

import com.bionote.user.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class TemplateRecordIntegrationTest {
    @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;@Autowired UserRepository users;
    @BeforeEach void clean(){jdbc.update("UPDATE experiment_records SET current_review_id=NULL,final_revision_id=NULL");jdbc.update("DELETE FROM revision_attachments");jdbc.update("DELETE FROM reviews");jdbc.update("DELETE FROM record_revisions");jdbc.update("DELETE FROM attachments");jdbc.update("DELETE FROM experiment_records");jdbc.update("DELETE FROM template_fields WHERE template_id IN (SELECT id FROM record_templates WHERE scope='PERSONAL')");jdbc.update("DELETE FROM record_templates WHERE scope='PERSONAL'");jdbc.update("DELETE FROM audit_events");jdbc.update("DELETE FROM notifications");jdbc.update("DELETE FROM project_invitations");jdbc.update("DELETE FROM project_members");jdbc.update("DELETE FROM projects");users.deleteAll();}
    private String register(String name,String email)throws Exception{return mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\""+name+"\",\"email\":\""+email+"\",\"password\":\"Password123!\"}")).andReturn().getResponse().getContentAsString().split("\\\"accessToken\\\":\\\"")[1].split("\\\"")[0];}
    private String project(String token)throws Exception{return mvc.perform(post("/api/v1/projects").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"记录项目\"}")).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];}
    private String personalTemplate(String token,String name)throws Exception{String body="{\"name\":\""+name+"\",\"experimentType\":\"PCR\",\"category\":\"分子\",\"description\":\"模板\",\"fields\":[{\"fieldKey\":\"amount\",\"label\":\"用量\",\"fieldType\":\"NUMBER\",\"required\":true,\"defaultValue\":2},{\"fieldKey\":\"result\",\"label\":\"结果\",\"fieldType\":\"SELECT\",\"required\":true,\"options\":[\"成功\",\"失败\"]}]}";return mvc.perform(post("/api/v1/templates").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];}
    private String record(String token,String project,String template)throws Exception{return mvc.perform(post("/api/v1/records").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"projectId\":\""+project+"\",\"templateId\":"+(template==null?"null":"\""+template+"\"")+",\"title\":\"PCR 记录\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"验证扩增\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];}
    private String addMember(String owner,String project,String memberToken,String email)throws Exception{String invite=mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+email+"\"}")).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];mvc.perform(post("/api/v1/invitations/"+invite+"/accept").header("Authorization","Bearer "+memberToken)).andExpect(status().isOk());return jdbc.queryForObject("SELECT user_id FROM project_members WHERE project_id=? AND role='MEMBER'",String.class,project);}

    @Test void personalTemplateIsOwnerIsolatedAndValidated()throws Exception{String a=register("A","a@example.com"),b=register("B","b@example.com");String id=personalTemplate(a,"我的模板");mvc.perform(get("/api/v1/templates/"+id).header("Authorization","Bearer "+b)).andExpect(status().isNotFound());mvc.perform(put("/api/v1/templates/10000000-0000-0000-0000-000000000001").header("Authorization","Bearer "+a).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"改系统\",\"version\":1,\"fields\":[]}")).andExpect(status().isForbidden());mvc.perform(post("/api/v1/templates").header("Authorization","Bearer "+a).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"非法\",\"fields\":[{\"fieldKey\":\"x\",\"label\":\"选项\",\"fieldType\":\"SELECT\",\"required\":false,\"options\":[]}]}" )).andExpect(status().isBadRequest());}

    @Test void templateSnapshotSurvivesTemplateUpdateAndDelete()throws Exception{String a=register("A","a@example.com");String p=project(a),t=personalTemplate(a,"快照模板"),r=record(a,p,t);String before=mvc.perform(get("/api/v1/records/"+r).header("Authorization","Bearer "+a)).andExpect(jsonPath("$.data.templateSnapshot.name").value("快照模板")).andReturn().getResponse().getContentAsString();mvc.perform(delete("/api/v1/templates/"+t).header("Authorization","Bearer "+a)).andExpect(status().isNoContent());String after=mvc.perform(get("/api/v1/records/"+r).header("Authorization","Bearer "+a)).andExpect(status().isOk()).andExpect(jsonPath("$.data.templateSnapshot.name").value("快照模板")).andReturn().getResponse().getContentAsString();assertThat(after).contains("amount");assertThat(before).contains("amount");}

    @Test void reviewerCannotCreateAndOtherMemberCannotEdit()throws Exception{String owner=register("A","a@example.com"),member=register("B","b@example.com");String p=project(owner);String memberId=addMember(owner,p,member,"b@example.com");mvc.perform(patch("/api/v1/projects/"+p+"/members/"+memberId+"/role").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"role\":\"REVIEWER\"}")).andExpect(status().isOk());mvc.perform(post("/api/v1/records").header("Authorization","Bearer "+member).contentType(MediaType.APPLICATION_JSON).content("{\"projectId\":\""+p+"\",\"title\":\"不允许\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"测试\"}")).andExpect(status().isForbidden());String ownerRecord=record(owner,p,null);mvc.perform(put("/api/v1/records/"+ownerRecord).header("Authorization","Bearer "+member).contentType(MediaType.APPLICATION_JSON).content("{\"version\":0,\"title\":\"越权\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"测试\",\"fieldValues\":{},\"contentJson\":{},\"contentHtml\":\"\"}")).andExpect(status().isForbidden());}

    @Test void optimisticLockAndSanitizationProtectUpdates()throws Exception{String a=register("A","a@example.com");String r=record(a,project(a),null);String update="{\"version\":0,\"title\":\"更新\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"测试\",\"fieldValues\":{},\"contentJson\":{\"type\":\"doc\"},\"contentHtml\":\"<p onclick='x()'>正文</p><script>alert(1)</script>\"}";mvc.perform(put("/api/v1/records/"+r).header("Authorization","Bearer "+a).contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isOk()).andExpect(jsonPath("$.data.contentHtml").value("<p>正文</p>"));mvc.perform(put("/api/v1/records/"+r).header("Authorization","Bearer "+a).contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("OPTIMISTIC_LOCK_CONFLICT"));}

    @Test void softDeleteAndArchiveGuardAreReal()throws Exception{String a=register("A","a@example.com");String p=project(a),r=record(a,p,null);mvc.perform(post("/api/v1/projects/"+p+"/archive").header("Authorization","Bearer "+a)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("PROJECT_ARCHIVE_BLOCKED"));mvc.perform(delete("/api/v1/records/"+r).header("Authorization","Bearer "+a)).andExpect(status().isNoContent());mvc.perform(get("/api/v1/records/"+r).header("Authorization","Bearer "+a)).andExpect(status().isNotFound());mvc.perform(post("/api/v1/projects/"+p+"/archive").header("Authorization","Bearer "+a)).andExpect(status().isOk());}

    @Test void memberRoleChangeIsBlockedByUnfinishedRecord()throws Exception{String owner=register("A","a@example.com"),member=register("B","b@example.com");String p=project(owner),memberId=addMember(owner,p,member,"b@example.com");record(member,p,null);mvc.perform(patch("/api/v1/projects/"+p+"/members/"+memberId+"/role").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"role\":\"REVIEWER\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("MEMBER_ROLE_BLOCKED"));}
    @Test void reservationSupportsAttachmentAndCanBeDiscarded()throws Exception{String token=register("A","a@example.com"),p=project(token);String body=mvc.perform(post("/api/v1/records/reservations").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"projectId\":\""+p+"\",\"templateId\":null}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.provisional").value(true)).andReturn().getResponse().getContentAsString();String id=body.split("\\\"id\\\":\\\"")[1].split("\\\"")[0];mvc.perform(get("/api/v1/records").header("Authorization","Bearer "+token)).andExpect(jsonPath("$.data").isEmpty());MockMultipartFile file=new MockMultipartFile("file","draft.png","image/png",new byte[]{(byte)0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0});mvc.perform(multipart("/api/v1/records/"+id+"/attachments").file(file).header("Authorization","Bearer "+token)).andExpect(status().isOk());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM attachments WHERE record_id=?",Long.class,id)).isEqualTo(1);mvc.perform(delete("/api/v1/records/"+id+"/reservation").header("Authorization","Bearer "+token)).andExpect(status().isNoContent());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM experiment_records WHERE id=?",Long.class,id)).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM attachments WHERE record_id=?",Long.class,id)).isZero();}

    @Test void firstReservationSaveCreatesOnceAndIdenticalSaveIsNoOp()throws Exception{String token=register("A","a@example.com"),p=project(token);String body=mvc.perform(post("/api/v1/records/reservations").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"projectId\":\""+p+"\"}")).andReturn().getResponse().getContentAsString();String id=body.split("\\\"id\\\":\\\"")[1].split("\\\"")[0];String update="{\"version\":0,\"title\":\"预留记录\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"验证预留\",\"fieldValues\":{},\"contentJson\":{},\"contentHtml\":\"\"}";mvc.perform(put("/api/v1/records/"+id).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isOk()).andExpect(jsonPath("$.data.provisional").value(false)).andExpect(jsonPath("$.data.version").value(1));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_events WHERE record_id=? AND event_type='RECORD_CREATED'",Long.class,id)).isEqualTo(1);String same=update.replace("\"version\":0","\"version\":1");mvc.perform(put("/api/v1/records/"+id).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content(same)).andExpect(status().isOk()).andExpect(jsonPath("$.data.version").value(1));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_events WHERE record_id=? AND event_type='RECORD_UPDATED'",Long.class,id)).isZero();}
}
