package com.bionote.project;

import com.bionote.user.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class ProjectCollaborationIntegrationTest {
    @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc; @Autowired UserRepository users;
    @BeforeEach void clean(){jdbc.update("UPDATE experiment_records SET current_review_id=NULL,final_revision_id=NULL");jdbc.update("DELETE FROM revision_attachments");jdbc.update("DELETE FROM reviews");jdbc.update("DELETE FROM record_revisions");jdbc.update("DELETE FROM attachments");jdbc.update("DELETE FROM experiment_records");jdbc.update("DELETE FROM template_fields WHERE template_id IN (SELECT id FROM record_templates WHERE scope='PERSONAL')");jdbc.update("DELETE FROM record_templates WHERE scope='PERSONAL'");jdbc.update("DELETE FROM audit_events");jdbc.update("DELETE FROM notifications");jdbc.update("DELETE FROM project_invitations");jdbc.update("DELETE FROM project_members");jdbc.update("DELETE FROM projects");users.deleteAll();}
    private String register(String name,String email)throws Exception{return mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\""+name+"\",\"email\":\""+email+"\",\"password\":\"Password123!\"}" )).andExpect(status().isOk()).andReturn().getResponse().getContentAsString().split("\\\"accessToken\\\":\\\"")[1].split("\\\"")[0];}
    private String createProject(String token)throws Exception{return mvc.perform(post("/api/v1/projects").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"演示项目\",\"description\":\"真实项目\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.currentUserRole").value("OWNER")).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];}

    @Test void nonMemberCannotGuessProjectUrl() throws Exception {String owner=register("A","a@example.com"),outsider=register("X","x@example.com");String project=createProject(owner);mvc.perform(get("/api/v1/projects/"+project).header("Authorization","Bearer "+outsider)).andExpect(status().isNotFound());}

    @Test void invitationAcceptanceCreatesOneMemberAndNotification() throws Exception {String owner=register("A","a@example.com"),member=register("B","b@example.com");String project=createProject(owner);String invite=mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"b@example.com\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];mvc.perform(post("/api/v1/invitations/"+invite+"/accept").header("Authorization","Bearer "+member)).andExpect(status().isOk()).andExpect(jsonPath("$.data.currentUserRole").value("MEMBER"));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM project_members WHERE project_id=?",Long.class,project)).isEqualTo(2);mvc.perform(post("/api/v1/invitations/"+invite+"/accept").header("Authorization","Bearer "+member)).andExpect(status().isConflict());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM project_members WHERE project_id=?",Long.class,project)).isEqualTo(2);}

    @Test void ownerCannotInviteInvalidTargetsOrDuplicatePending() throws Exception {String owner=register("A","a@example.com");register("B","b@example.com");String project=createProject(owner);mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"none@example.com\"}")).andExpect(status().isNotFound());mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"a@example.com\"}")).andExpect(status().isConflict());mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"b@example.com\"}")).andExpect(status().isOk());mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"b@example.com\"}")).andExpect(status().isConflict());}

    @Test void membersCannotManageAndOwnerIsImmutable() throws Exception {String owner=register("A","a@example.com"),member=register("B","b@example.com");String project=createProject(owner);String invite=mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"b@example.com\"}")).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];mvc.perform(post("/api/v1/invitations/"+invite+"/accept").header("Authorization","Bearer "+member)).andExpect(status().isOk());String ownerId=jdbc.queryForObject("SELECT owner_id FROM projects WHERE id=?",String.class,project);mvc.perform(post("/api/v1/projects/"+project+"/archive").header("Authorization","Bearer "+member)).andExpect(status().isForbidden());mvc.perform(patch("/api/v1/projects/"+project+"/members/"+ownerId+"/role").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"role\":\"REVIEWER\"}")).andExpect(status().isConflict());}

    @Test void emptyProjectArchiveIsIdempotentAndBlocksWrites() throws Exception {String owner=register("A","a@example.com");register("B","b@example.com");String project=createProject(owner);mvc.perform(post("/api/v1/projects/"+project+"/archive").header("Authorization","Bearer "+owner)).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("ARCHIVED"));mvc.perform(post("/api/v1/projects/"+project+"/archive").header("Authorization","Bearer "+owner)).andExpect(status().isOk());assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_events WHERE event_type='PROJECT_ARCHIVED' AND project_id=?",Long.class,project)).isEqualTo(1);mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"b@example.com\"}")).andExpect(status().isConflict());}

    @Test void roleChangeAndRemovalAreOwnerOnly() throws Exception {String owner=register("A","a@example.com"),member=register("B","b@example.com");String project=createProject(owner);String invite=mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\"b@example.com\"}")).andReturn().getResponse().getContentAsString().split("\\\"id\\\":\\\"")[1].split("\\\"")[0];mvc.perform(post("/api/v1/invitations/"+invite+"/accept").header("Authorization","Bearer "+member)).andExpect(status().isOk());String memberId=jdbc.queryForObject("SELECT user_id FROM project_members WHERE project_id=? AND role='MEMBER'",String.class,project);mvc.perform(patch("/api/v1/projects/"+project+"/members/"+memberId+"/role").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"role\":\"REVIEWER\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.role").value("REVIEWER"));mvc.perform(post("/api/v1/projects/"+project+"/members/"+memberId+"/remove").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isNoContent());mvc.perform(get("/api/v1/projects/"+project).header("Authorization","Bearer "+member)).andExpect(status().isNotFound());}
    @Test void projectPersistsSummaryAndDetailedDescription()throws Exception{String owner=register("A","a@example.com");String response=mvc.perform(post("/api/v1/projects").header("Authorization","Bearer "+owner).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"详细项目\",\"description\":\"卡片简介\",\"detailedDescription\":\"研究背景与完整实验范围\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.description").value("卡片简介")).andExpect(jsonPath("$.data.detailedDescription").value("研究背景与完整实验范围")).andReturn().getResponse().getContentAsString();String project=response.split("\\\"id\\\":\\\"")[1].split("\\\"")[0];mvc.perform(get("/api/v1/projects/"+project).header("Authorization","Bearer "+owner)).andExpect(status().isOk()).andExpect(jsonPath("$.data.detailedDescription").value("研究背景与完整实验范围"));}
}
