package com.bionote.template;

import com.bionote.collaboration.EventService;
import com.bionote.common.ApiException;
import com.bionote.common.PagedResponse;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

@Service
public class TemplateService {
    private static final Set<String> TYPES=Set.of("SINGLE_LINE_TEXT","MULTI_LINE_TEXT","NUMBER","DATE","SELECT","FILE");
    private final JdbcTemplate jdbc; private final ObjectMapper json; private final EventService events;
    public TemplateService(JdbcTemplate jdbc,ObjectMapper json,EventService events){this.jdbc=jdbc;this.json=json;this.events=events;}
    private String encode(Object v){try{return v==null?null:json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException(e);}}
    private Object decodeValue(String value){try{return value==null?null:json.readValue(value,Object.class);}catch(Exception e){return null;}}
    private List<String> decodeOptions(String value){try{return value==null?List.of():json.readValue(value,new TypeReference<>(){});}catch(Exception e){return List.of();}}

    public PagedResponse<TemplateDtos.View> list(UUID user,String scope,String category,String keyword,int page,int size){page=Math.max(0,page);size=Math.max(1,Math.min(100,size));String like="%"+esc(keyword)+"%";String where=" FROM record_templates WHERE deleted_at IS NULL AND (scope='SYSTEM' OR owner_id=?) AND (? IS NULL OR scope=?) AND (? IS NULL OR category=?) AND (LOWER(name) LIKE ? ESCAPE '!' OR LOWER(COALESCE(description,'')) LIKE ? ESCAPE '!')";String sc=scope==null||scope.isBlank()?null:scope,cat=category==null||category.isBlank()?null:category;long total=jdbc.queryForObject("SELECT COUNT(*)"+where,Long.class,user.toString(),sc,sc,cat,cat,like,like);List<TemplateDtos.View> items=jdbc.query("SELECT *"+where+" ORDER BY scope DESC,updated_at DESC,id DESC LIMIT ? OFFSET ?",(rs,n)->viewRow(user,rs.getString("id")),user.toString(),sc,sc,cat,cat,like,like,size,page*size);return PagedResponse.of(items,page,size,total);}
    public TemplateDtos.View get(UUID user,UUID id){Map<String,Object> row=visible(user,id);return viewRow(user,row.get("id").toString());}

    @Transactional public TemplateDtos.View create(UUID user,TemplateDtos.SaveRequest request){validate(request);UUID id=UUID.randomUUID();Instant now=Instant.now();String normalized=normal(request.name());try{jdbc.update("INSERT INTO record_templates(id,scope,owner_id,name,name_normalized,active_name_key,experiment_type,category,description,created_at,updated_at,version) VALUES(?,'PERSONAL',?,?,?,?,?,?,?,?,?,0)",id.toString(),user.toString(),request.name().trim(),normalized,user+":"+normalized,trim(request.experimentType()),trim(request.category()),trim(request.description()),Timestamp.from(now),Timestamp.from(now));}catch(DuplicateKeyException e){throw duplicateName();}saveFields(id,request.fields());events.audit(user,null,null,"TEMPLATE_CREATED","TEMPLATE",id,Map.of("name",request.name().trim()));return get(user,id);}

    @Transactional public TemplateDtos.View update(UUID user,UUID id,TemplateDtos.SaveRequest request){validate(request);Map<String,Object> row=owned(user,id);long version=((Number)row.get("version")).longValue();if(request.version()==null||request.version()!=version)throw new ApiException(HttpStatus.CONFLICT,"OPTIMISTIC_LOCK_CONFLICT","模板已被其他页面更新");String normalized=normal(request.name());try{int changed=jdbc.update("UPDATE record_templates SET name=?,name_normalized=?,active_name_key=?,experiment_type=?,category=?,description=?,updated_at=?,version=version+1 WHERE id=? AND owner_id=? AND deleted_at IS NULL AND version=?",request.name().trim(),normalized,user+":"+normalized,trim(request.experimentType()),trim(request.category()),trim(request.description()),Timestamp.from(Instant.now()),id.toString(),user.toString(),version);if(changed==0)throw new ApiException(HttpStatus.CONFLICT,"OPTIMISTIC_LOCK_CONFLICT","模板已被其他页面更新");}catch(DuplicateKeyException e){throw duplicateName();}jdbc.update("DELETE FROM template_fields WHERE template_id=?",id.toString());saveFields(id,request.fields());events.audit(user,null,null,"TEMPLATE_UPDATED","TEMPLATE",id,Map.of("name",request.name().trim()));return get(user,id);}

    @Transactional public void delete(UUID user,UUID id){Map<String,Object> row=owned(user,id);if(row.get("deleted_at")!=null)return;jdbc.update("UPDATE record_templates SET deleted_at=?,active_name_key=NULL,updated_at=?,version=version+1 WHERE id=?",Timestamp.from(Instant.now()),Timestamp.from(Instant.now()),id.toString());events.audit(user,null,null,"TEMPLATE_DELETED","TEMPLATE",id,Map.of("name",row.get("name")));}
    @Transactional public TemplateDtos.View copy(UUID user,UUID source){TemplateDtos.View original=get(user,source);String base=original.name()+" 副本",name=base;int n=2;while(Boolean.TRUE.equals(jdbc.queryForObject("SELECT COUNT(*)>0 FROM record_templates WHERE owner_id=? AND active_name_key=?",Boolean.class,user.toString(),user+":"+normal(name))))name=base+" "+n++;List<TemplateDtos.FieldRequest> fields=original.fields().stream().map(f->new TemplateDtos.FieldRequest(f.fieldKey(),f.label(),f.fieldType(),f.required(),f.placeholder(),f.defaultValue(),f.options())).toList();return create(user,new TemplateDtos.SaveRequest(name,original.experimentType(),original.category(),original.description(),fields,null));}

    private void validate(TemplateDtos.SaveRequest request){Set<String> keys=new HashSet<>(),labels=new HashSet<>();for(var f:request.fields()){String key=f.fieldKey().trim();if(!keys.add(key))throw validation("fields","字段 key 不能重复");if(!labels.add(f.label().trim().toLowerCase(Locale.ROOT)))throw validation("fields","字段名称不能重复");if(!TYPES.contains(f.fieldType()))throw validation("fields","不支持的字段类型: "+f.fieldType());if("FILE".equals(f.fieldType())&&f.defaultValue()!=null)throw validation("fields","文件字段不能设置默认值");if("SELECT".equals(f.fieldType())){List<String> opts=f.options()==null?List.of():f.options().stream().map(String::trim).filter(v->!v.isBlank()).distinct().toList();if(opts.isEmpty())throw validation("fields","下拉字段至少需要一个选项");if(f.defaultValue()!=null&&!opts.contains(f.defaultValue().toString()))throw validation("fields","下拉默认值必须来自选项");}}}
    private void saveFields(UUID template,List<TemplateDtos.FieldRequest> fields){for(int i=0;i<fields.size();i++){var f=fields.get(i);List<String> opts="SELECT".equals(f.fieldType())?f.options().stream().map(String::trim).filter(v->!v.isBlank()).distinct().toList():List.of();jdbc.update("INSERT INTO template_fields(id,template_id,field_key,label,field_type,required,sort_order,placeholder,default_value_json,options_json) VALUES(?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),template.toString(),f.fieldKey().trim(),f.label().trim(),f.fieldType(),f.required(),i,trim(f.placeholder()),encode(f.defaultValue()),opts.isEmpty()?null:encode(opts));}}
    private TemplateDtos.View viewRow(UUID user,String id){Map<String,Object> r=jdbc.queryForMap("SELECT * FROM record_templates WHERE id=?",id);List<TemplateDtos.FieldView> fields=jdbc.query("SELECT * FROM template_fields WHERE template_id=? ORDER BY sort_order",(rs,n)->new TemplateDtos.FieldView(UUID.fromString(rs.getString("id")),rs.getString("field_key"),rs.getString("label"),rs.getString("field_type"),rs.getBoolean("required"),rs.getInt("sort_order"),rs.getString("placeholder"),decodeValue(rs.getString("default_value_json")),decodeOptions(rs.getString("options_json"))),id);UUID owner=r.get("owner_id")==null?null:UUID.fromString(r.get("owner_id").toString());boolean editable=user.equals(owner);return new TemplateDtos.View(UUID.fromString(id),r.get("scope").toString(),owner,r.get("name").toString(),str(r.get("experiment_type")),str(r.get("category")),str(r.get("description")),((Timestamp)r.get("created_at")).toInstant(),((Timestamp)r.get("updated_at")).toInstant(),((Number)r.get("version")).longValue(),fields,editable,editable);}
    private Map<String,Object> visible(UUID user,UUID id){List<Map<String,Object>> rows=jdbc.queryForList("SELECT * FROM record_templates WHERE id=? AND deleted_at IS NULL AND (scope='SYSTEM' OR owner_id=?)",id.toString(),user.toString());if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","模板不存在或无权访问");return rows.get(0);}
    private Map<String,Object> owned(UUID user,UUID id){Map<String,Object> r=visible(user,id);if(!"PERSONAL".equals(r.get("scope"))||!user.toString().equals(r.get("owner_id").toString()))throw new ApiException(HttpStatus.FORBIDDEN,"ACCESS_DENIED","系统模板或他人模板不可修改");return r;}
    private ApiException duplicateName(){return new ApiException(HttpStatus.CONFLICT,"DUPLICATE_RESOURCE","个人模板名称已存在",Map.of("name","个人模板名称已存在"));}
    private ApiException validation(String field,String message){return new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","请检查模板字段",Map.of(field,message));}
    private String normal(String v){return v.trim().toLowerCase(Locale.ROOT);} private String trim(String v){return v==null||v.isBlank()?null:v.trim();}private String str(Object v){return v==null?null:v.toString();}private String esc(String v){return v==null?"":normal(v).replace("!","!!").replace("%","!%").replace("_","!_");}
}
