package com.bionote.activity;

import com.bionote.user.UserRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class ActivitySearchIntegrationTest {
    @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;@Autowired UserRepository users;@Autowired ObjectMapper json;
    @BeforeEach void clean(){jdbc.update("UPDATE experiment_records SET current_review_id=NULL,final_revision_id=NULL");jdbc.update("DELETE FROM revision_attachments");jdbc.update("DELETE FROM reviews");jdbc.update("DELETE FROM record_revisions");jdbc.update("DELETE FROM attachments");jdbc.update("DELETE FROM experiment_records");jdbc.update("DELETE FROM template_fields WHERE template_id IN (SELECT id FROM record_templates WHERE scope='PERSONAL')");jdbc.update("DELETE FROM record_templates WHERE scope='PERSONAL'");jdbc.update("DELETE FROM audit_events");jdbc.update("DELETE FROM notifications");jdbc.update("DELETE FROM project_invitations");jdbc.update("DELETE FROM project_members");jdbc.update("DELETE FROM projects");users.deleteAll();}
    private String register(String name,String email)throws Exception{return value(mvc.perform(post("/api/v1/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"displayName\":\""+name+"\",\"email\":\""+email+"\",\"password\":\"Password123!\"}")).andExpect(status().isOk()).andReturn(),"data.accessToken");}
    private String project(String token,String name)throws Exception{return value(mvc.perform(post("/api/v1/projects").header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\""+name+"\",\"description\":\"PCR 项目描述\"}")).andExpect(status().isOk()).andReturn(),"data.id");}
    private String invite(String owner,String project,String email)throws Exception{return value(mvc.perform(post("/api/v1/projects/"+project+"/invitations").header("Authorization",bearer(owner)).contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+email+"\"}")).andExpect(status().isOk()).andReturn(),"data.id");}
    private void accept(String token,String invitation)throws Exception{mvc.perform(post("/api/v1/invitations/"+invitation+"/accept").header("Authorization",bearer(token))).andExpect(status().isOk());}
    private String record(String token,String project,String title)throws Exception{return value(mvc.perform(post("/api/v1/records").header("Authorization",bearer(token)).contentType(MediaType.APPLICATION_JSON).content("{\"projectId\":\""+project+"\",\"title\":\""+title+"\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"搜索 PCR 正文\"}")).andExpect(status().isOk()).andReturn(),"data.id");}
    private String upload(String token,String record,String name)throws Exception{MockMultipartFile f=new MockMultipartFile("file",name,"image/png",new byte[]{(byte)0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0});return value(mvc.perform(multipart("/api/v1/records/"+record+"/attachments").file(f).header("Authorization",bearer(token))).andExpect(status().isOk()).andReturn(),"data.id");}
    private String value(MvcResult result,String path)throws Exception{JsonNode node=json.readTree(result.getResponse().getContentAsString());for(String p:path.split("\\."))node=node.get(p);return node.asText();}
    private String bearer(String token){return "Bearer "+token;}

    @Test void notificationsExposeControlledActionsAndReadState()throws Exception{String owner=register("A","a@example.com"),member=register("B","b@example.com"),p=project(owner,"通知项目"),invitation=invite(owner,p,"b@example.com");mvc.perform(get("/api/v1/notifications").header("Authorization",bearer(member))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].target.type").value("INVITATION")).andExpect(jsonPath("$.data[0].target.id").value(invitation)).andExpect(jsonPath("$.data[0].actions[0]").value("ACCEPT")).andExpect(jsonPath("$.data[0].stale").value(false));String notification=jdbc.queryForObject("SELECT id FROM notifications WHERE recipient_id=(SELECT id FROM users WHERE email_normalized='b@example.com')",String.class);mvc.perform(patch("/api/v1/notifications/"+notification+"/read").header("Authorization",bearer(member))).andExpect(status().isNoContent());mvc.perform(patch("/api/v1/notifications/"+notification+"/read").header("Authorization",bearer(member))).andExpect(status().isNoContent());accept(member,invitation);mvc.perform(get("/api/v1/notifications").header("Authorization",bearer(member))).andExpect(jsonPath("$.data[0].actions").isEmpty()).andExpect(jsonPath("$.data[0].stale").value(true));mvc.perform(post("/api/v1/notifications/read-all").header("Authorization",bearer(member))).andExpect(status().isNoContent());mvc.perform(get("/api/v1/notifications/unread-count").header("Authorization",bearer(member))).andExpect(jsonPath("$.data.count").value(0));}

    @Test void dashboardOnlyContainsCurrentlyActionableTasks()throws Exception{String owner=register("A","a@example.com"),creator=register("B","b@example.com"),reviewer=register("C","c@example.com"),p=project(owner,"待办项目"),creatorInvite=invite(owner,p,"b@example.com");mvc.perform(get("/api/v1/dashboard/tasks").header("Authorization",bearer(creator))).andExpect(jsonPath("$.data[0].type").value("PROJECT_INVITATION"));accept(creator,creatorInvite);String reviewerInvite=invite(owner,p,"c@example.com");accept(reviewer,reviewerInvite);String reviewerId=jdbc.queryForObject("SELECT id FROM users WHERE email_normalized='c@example.com'",String.class);mvc.perform(patch("/api/v1/projects/"+p+"/members/"+reviewerId+"/role").header("Authorization",bearer(owner)).contentType(MediaType.APPLICATION_JSON).content("{\"role\":\"REVIEWER\"}")).andExpect(status().isOk());String r=record(creator,p,"待审核 PCR");MvcResult submission=mvc.perform(post("/api/v1/records/"+r+"/submissions").header("Authorization",bearer(creator)).contentType(MediaType.APPLICATION_JSON).content("{\"reviewerId\":\""+reviewerId+"\",\"expectedRecordVersion\":0}")).andExpect(status().isOk()).andReturn();String review=value(submission,"data.review.id");mvc.perform(get("/api/v1/dashboard/tasks").header("Authorization",bearer(reviewer))).andExpect(jsonPath("$.data[0].type").value("PENDING_REVIEW")).andExpect(jsonPath("$.data[0].revisionNo").value(1));mvc.perform(post("/api/v1/records/"+r+"/reviews/"+review+"/request-changes").header("Authorization",bearer(reviewer)).contentType(MediaType.APPLICATION_JSON).content("{\"comment\":\"补充对照组\"}")).andExpect(status().isOk());mvc.perform(get("/api/v1/dashboard/tasks").header("Authorization",bearer(reviewer))).andExpect(jsonPath("$.data").isEmpty());mvc.perform(get("/api/v1/dashboard/tasks").header("Authorization",bearer(creator))).andExpect(jsonPath("$.data[0].type").value("CHANGES_REQUESTED")).andExpect(jsonPath("$.data[0].action").value("继续修改"));}

    @Test void globalSearchIsPermissionScopedFilteredAndEscapesWildcards()throws Exception{String owner=register("A","a@example.com"),member=register("B","b@example.com"),outsider=register("X","x@example.com"),p=project(owner,"PCR 可见项目"),i=invite(owner,p,"b@example.com");accept(member,i);String visible=record(member,p,"100% PCR 记录");upload(member,visible,"PCR-结果.png");String hiddenProject=project(outsider,"秘密 PCR 项目");record(outsider,hiddenProject,"秘密 PCR 记录");mvc.perform(get("/api/v1/search").header("Authorization",bearer(member)).param("keyword","PCR").param("entityType","RECORD")).andExpect(status().isOk()).andExpect(jsonPath("$.meta.total").value(1)).andExpect(jsonPath("$.data[0].title").value("100% PCR 记录"));mvc.perform(get("/api/v1/search").header("Authorization",bearer(member)).param("keyword","%").param("entityType","RECORD")).andExpect(jsonPath("$.meta.total").value(1));mvc.perform(get("/api/v1/search").header("Authorization",bearer(member)).param("keyword","PCR").param("entityType","ATTACHMENT")).andExpect(jsonPath("$.meta.total").value(1)).andExpect(jsonPath("$.data[0].target.type").value("RECORD_ATTACHMENT")).andExpect(jsonPath("$.data[0].target.id").value(visible));mvc.perform(delete("/api/v1/records/"+visible).header("Authorization",bearer(member))).andExpect(status().isNoContent());mvc.perform(get("/api/v1/search").header("Authorization",bearer(member)).param("keyword","PCR").param("entityType","ATTACHMENT")).andExpect(jsonPath("$.meta.total").value(0));}

    @Test void auditTimelineAndAttachmentSummaryAreReadOnlyAndMemberScoped()throws Exception{String owner=register("A","a@example.com"),member=register("B","b@example.com"),outsider=register("X","x@example.com"),p=project(owner,"审计项目"),i=invite(owner,p,"b@example.com");accept(member,i);String r=record(member,p,"审计 PCR"),attachment=upload(member,r,"审计.png");mvc.perform(get("/api/v1/projects/"+p+"/audit-events").header("Authorization",bearer(member))).andExpect(status().isOk()).andExpect(jsonPath("$.meta.totalElements").value(org.hamcrest.Matchers.greaterThan(0))).andExpect(jsonPath("$.data[0].metadata.storageKey").doesNotExist());mvc.perform(get("/api/v1/projects/"+p+"/audit-events").header("Authorization",bearer(outsider))).andExpect(status().isNotFound());mvc.perform(get("/api/v1/projects/"+p+"/attachments").header("Authorization",bearer(member))).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].id").value(attachment)).andExpect(jsonPath("$.data[0].recordId").value(r));mvc.perform(delete("/api/v1/projects/"+p+"/audit-events").header("Authorization",bearer(owner))).andExpect(status().isMethodNotAllowed());}
    @Test void timelineOmitsRepeatedRecordSavesButIncludesAttachmentUploads()throws Exception{String owner=register("A","a@example.com"),p=project(owner,"去重时间线项目"),r=record(owner,p,"初始记录");mvc.perform(put("/api/v1/records/"+r).header("Authorization",bearer(owner)).contentType(MediaType.APPLICATION_JSON).content("{\"version\":0,\"title\":\"第一次保存\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"更新目的\",\"fieldValues\":{},\"contentJson\":{},\"contentHtml\":\"\"}")).andExpect(status().isOk());mvc.perform(put("/api/v1/records/"+r).header("Authorization",bearer(owner)).contentType(MediaType.APPLICATION_JSON).content("{\"version\":1,\"title\":\"第二次保存\",\"experimentType\":\"PCR\",\"experimentDate\":\"2026-07-23\",\"purpose\":\"再次更新\",\"fieldValues\":{},\"contentJson\":{},\"contentHtml\":\"\"}")).andExpect(status().isOk());upload(owner,r,"扩增结果.png");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM audit_events WHERE record_id=? AND event_type='RECORD_UPDATED'",Long.class,r)).isEqualTo(2);mvc.perform(get("/api/v1/projects/"+p+"/audit-events").header("Authorization",bearer(owner))).andExpect(status().isOk()).andExpect(jsonPath("$.data[*].eventType",org.hamcrest.Matchers.hasItem("ATTACHMENT_UPLOADED"))).andExpect(jsonPath("$.data[*].eventType",org.hamcrest.Matchers.not(org.hamcrest.Matchers.hasItem("RECORD_UPDATED"))));}
}
