package com.bionote.audit;

import com.bionote.common.ApiException;
import com.bionote.common.PagedResponse;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;

@Service
public class AuditService {
    private static final Set<String> SAFE_KEYS=Set.of("name","title","code","email","role","from","to","reason","revisionNo","reviewerId","inviteeUserId","filename","sizeBytes","comment");
    private static final Set<String> TIMELINE_EVENTS=Set.of("PROJECT_CREATED","PROJECT_ARCHIVED","INVITATION_CREATED","INVITATION_ACCEPTED","INVITATION_REJECTED","INVITATION_EXPIRED","MEMBER_ROLE_CHANGED","MEMBER_REMOVED","RECORD_CREATED","RECORD_DELETED","ATTACHMENT_UPLOADED","ATTACHMENT_DELETED","RECORD_SUBMITTED","REVIEW_CHANGES_REQUESTED","REVIEW_APPROVED","REVIEWER_REASSIGNED","RECORD_EXPORT_PREVIEW","RECORD_EXPORT_MARKDOWN","RECORD_EXPORT_PDF");
    private final JdbcTemplate jdbc;private final ObjectMapper json;public AuditService(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
    public record View(UUID id,String eventType,String targetType,UUID targetId,UUID recordId,UUID actorId,String actorName,Map<String,Object> metadata,Instant createdAt){}
    public record AttachmentSummary(UUID id,String filename,String mediaType,long sizeBytes,UUID recordId,String recordTitle,String recordCode,String uploaderName,Instant createdAt){}
    public PagedResponse<View> list(UUID user,UUID project,String eventType,UUID actor,LocalDate from,LocalDate to,int page,int size){requireMember(user,project);page=Math.max(0,page);size=Math.max(1,Math.min(100,size));String ev=blank(eventType)?null:eventType.trim();if(ev!=null&&!TIMELINE_EVENTS.contains(ev))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","不支持的时间线事件类型");Timestamp start=from==null?null:Timestamp.from(from.atStartOfDay(ZoneOffset.UTC).toInstant()),end=to==null?null:Timestamp.from(to.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant());String where=" FROM audit_events a LEFT JOIN users u ON u.id=a.actor_id WHERE a.project_id=? AND a.event_type IN ('PROJECT_CREATED','PROJECT_ARCHIVED','INVITATION_CREATED','INVITATION_ACCEPTED','INVITATION_REJECTED','INVITATION_EXPIRED','MEMBER_ROLE_CHANGED','MEMBER_REMOVED','RECORD_CREATED','RECORD_DELETED','ATTACHMENT_UPLOADED','ATTACHMENT_DELETED','RECORD_SUBMITTED','REVIEW_CHANGES_REQUESTED','REVIEW_APPROVED','REVIEWER_REASSIGNED','RECORD_EXPORT_PREVIEW','RECORD_EXPORT_MARKDOWN','RECORD_EXPORT_PDF') AND (? IS NULL OR a.event_type=?) AND (? IS NULL OR a.actor_id=?) AND (? IS NULL OR a.created_at>=?) AND (? IS NULL OR a.created_at<?)";List<Object>args=Arrays.asList(project.toString(),ev,ev,val(actor),val(actor),start,start,end,end);long total=jdbc.queryForObject("SELECT COUNT(*)"+where,Long.class,args.toArray());List<Object>paged=new ArrayList<>(args);paged.add(size);paged.add(page*size);List<View>data=jdbc.query("SELECT a.*,u.display_name actor_name"+where+" ORDER BY a.created_at DESC,a.id DESC LIMIT ? OFFSET ?",(rs,n)->new View(UUID.fromString(rs.getString("id")),rs.getString("event_type"),rs.getString("target_type"),UUID.fromString(rs.getString("target_id")),rs.getString("record_id")==null?null:UUID.fromString(rs.getString("record_id")),rs.getString("actor_id")==null?null:UUID.fromString(rs.getString("actor_id")),Objects.toString(rs.getString("actor_name"),"系统"),safe(rs.getString("metadata_json")),rs.getTimestamp("created_at").toInstant()),paged.toArray());return PagedResponse.of(data,page,size,total);}
    public PagedResponse<AttachmentSummary> attachments(UUID user,UUID project,int page,int size){requireMember(user,project);page=Math.max(0,page);size=Math.max(1,Math.min(100,size));long total=jdbc.queryForObject("SELECT COUNT(*) FROM attachments a JOIN experiment_records r ON r.id=a.record_id WHERE r.project_id=? AND r.deleted_at IS NULL AND r.provisional=FALSE AND a.deleted_at IS NULL",Long.class,project.toString());List<AttachmentSummary>data=jdbc.query("SELECT a.id,a.original_filename,a.media_type,a.size_bytes,a.created_at,r.id record_id,r.title,r.code,u.display_name FROM attachments a JOIN experiment_records r ON r.id=a.record_id JOIN users u ON u.id=a.uploader_id WHERE r.project_id=? AND r.deleted_at IS NULL AND r.provisional=FALSE AND a.deleted_at IS NULL ORDER BY a.created_at DESC,a.id DESC LIMIT ? OFFSET ?",(rs,n)->new AttachmentSummary(UUID.fromString(rs.getString("id")),rs.getString("original_filename"),rs.getString("media_type"),rs.getLong("size_bytes"),UUID.fromString(rs.getString("record_id")),rs.getString("title"),rs.getString("code"),rs.getString("display_name"),rs.getTimestamp("created_at").toInstant()),project.toString(),size,page*size);return PagedResponse.of(data,page,size,total);}
    private void requireMember(UUID user,UUID project){if(jdbc.queryForObject("SELECT COUNT(*) FROM project_members WHERE project_id=? AND user_id=?",Integer.class,project.toString(),user.toString())==0)throw new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","项目不存在或无权访问");}
    private Map<String,Object>safe(String value){try{Map<String,Object>raw=json.readValue(value,new TypeReference<>(){}),safe=new LinkedHashMap<>();raw.forEach((k,v)->{if(SAFE_KEYS.contains(k))safe.put(k,v);});return safe;}catch(Exception e){return Map.of();}}
    private boolean blank(String v){return v==null||v.isBlank();}private String val(UUID id){return id==null?null:id.toString();}
}
