package com.bionote.search;

import com.bionote.common.ApiException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import java.sql.Timestamp;
import java.util.*;

@Service
public class SearchService {
    private static final Set<String> TYPES=Set.of("ALL","PROJECT","RECORD","TEMPLATE","MEMBER","ATTACHMENT");
    private final JdbcTemplate jdbc;public SearchService(JdbcTemplate jdbc){this.jdbc=jdbc;}
    public SearchDtos.Response search(UUID user,String keyword,String entityType,UUID projectId,UUID creatorId,String recordStatus,int page,int size){String type=entityType==null?"ALL":entityType.toUpperCase(Locale.ROOT);if(!TYPES.contains(type))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","搜索类型不合法");String raw=keyword==null?"":keyword.trim();if(raw.length()>100)throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","搜索关键词不能超过 100 个字符");String like="%"+escape(raw.toLowerCase(Locale.ROOT))+"%";page=Math.max(0,page);size=Math.max(1,Math.min(100,size));List<Branch> branches=new ArrayList<>();if(type.equals("ALL")||type.equals("PROJECT"))branches.add(projects(user,projectId,creatorId,recordStatus,like));if(type.equals("ALL")||type.equals("RECORD"))branches.add(records(user,projectId,creatorId,recordStatus,like));if(type.equals("ALL")||type.equals("TEMPLATE"))branches.add(templates(user,projectId,creatorId,recordStatus,like));if(type.equals("ALL")||type.equals("MEMBER"))branches.add(members(user,projectId,creatorId,recordStatus,like));if(type.equals("ALL")||type.equals("ATTACHMENT"))branches.add(attachments(user,projectId,creatorId,recordStatus,like));String union=String.join(" UNION ALL ",branches.stream().map(Branch::sql).toList());List<Object>args=new ArrayList<>();branches.forEach(b->args.addAll(b.args()));Map<String,Long>counts=new LinkedHashMap<>();jdbc.query("SELECT entity_type,COUNT(*) total FROM ("+union+") search_count GROUP BY entity_type",rs->{counts.put(rs.getString("entity_type"),rs.getLong("total"));},args.toArray());long total=counts.values().stream().mapToLong(Long::longValue).sum();List<Object>paged=new ArrayList<>(args);paged.add(size);paged.add(page*size);List<SearchDtos.Result>data=jdbc.query("SELECT * FROM ("+union+") search_results ORDER BY updated_at DESC,id DESC LIMIT ? OFFSET ?",(rs,n)->{String entity=rs.getString("entity_type"),id=rs.getString("id"),targetId=rs.getString("target_id");Map<String,Object>target=switch(entity){case "PROJECT"->Map.of("type","PROJECT","id",targetId);case "TEMPLATE"->Map.of("type","TEMPLATE","id",targetId);case "MEMBER"->Map.of("type","PROJECT_MEMBERS","id",targetId);case "ATTACHMENT"->Map.of("type","RECORD_ATTACHMENT","id",targetId,"attachmentId",id);default->Map.of("type","RECORD","id",targetId);};return new SearchDtos.Result(entity,id,rs.getString("title"),Objects.toString(rs.getString("snippet"),""),rs.getString("project_id")==null?null:UUID.fromString(rs.getString("project_id")),rs.getString("project_name"),rs.getString("status"),rs.getTimestamp("updated_at")==null?null:rs.getTimestamp("updated_at").toInstant(),target);},paged.toArray());return new SearchDtos.Response(data,new SearchDtos.Meta(page,size,total,counts));}
    private Branch projects(UUID u,UUID p,UUID c,String status,String like){String sql="SELECT 'PROJECT' entity_type,p.id,p.name title,SUBSTRING(COALESCE(NULLIF(p.detailed_description,''),p.description,''),1,300) snippet,p.id project_id,p.name project_name,p.status,p.updated_at,p.id target_id FROM projects p JOIN project_members pm ON pm.project_id=p.id WHERE pm.user_id=? AND (? IS NULL OR p.id=?) AND (LOWER(p.name) LIKE ? ESCAPE '!' OR LOWER(COALESCE(p.description,'')) LIKE ? ESCAPE '!' OR LOWER(COALESCE(p.detailed_description,'')) LIKE ? ESCAPE '!')"+(c!=null||nonblank(status)?" AND 1=0":"");return new Branch(sql,Arrays.asList(u.toString(),v(p),v(p),like,like,like));}
    private Branch records(UUID u,UUID p,UUID c,String status,String like){String sql="SELECT 'RECORD' entity_type,r.id,r.title,SUBSTRING(COALESCE(NULLIF(r.content_plain_text,''),r.purpose),1,300) snippet,r.project_id,p.name project_name,r.status,r.updated_at,r.id target_id FROM experiment_records r JOIN projects p ON p.id=r.project_id JOIN project_members pm ON pm.project_id=r.project_id WHERE pm.user_id=? AND r.deleted_at IS NULL AND r.provisional=FALSE AND (? IS NULL OR r.project_id=?) AND (? IS NULL OR r.creator_id=?) AND (? IS NULL OR r.status=?) AND (LOWER(r.title) LIKE ? ESCAPE '!' OR LOWER(r.code) LIKE ? ESCAPE '!' OR LOWER(r.experiment_type) LIKE ? ESCAPE '!' OR LOWER(r.purpose) LIKE ? ESCAPE '!' OR LOWER(r.content_plain_text) LIKE ? ESCAPE '!' OR LOWER(r.field_values_json) LIKE ? ESCAPE '!')";String st=nonblank(status)?status:null;return new Branch(sql,Arrays.asList(u.toString(),v(p),v(p),v(c),v(c),st,st,like,like,like,like,like,like));}
    private Branch templates(UUID u,UUID p,UUID c,String status,String like){String sql="SELECT 'TEMPLATE' entity_type,t.id,t.name title,SUBSTRING(COALESCE(t.description,''),1,300) snippet,NULL project_id,NULL project_name,t.scope status,t.updated_at,t.id target_id FROM record_templates t WHERE t.deleted_at IS NULL AND (t.scope='SYSTEM' OR t.owner_id=?) AND (LOWER(t.name) LIKE ? ESCAPE '!' OR LOWER(COALESCE(t.description,'')) LIKE ? ESCAPE '!' OR LOWER(COALESCE(t.experiment_type,'')) LIKE ? ESCAPE '!')"+(p!=null||c!=null||nonblank(status)?" AND 1=0":"");return new Branch(sql,Arrays.asList(u.toString(),like,like,like));}
    private Branch members(UUID u,UUID p,UUID c,String status,String like){String sql="SELECT 'MEMBER' entity_type,u.id,u.display_name title,u.email_normalized snippet,pm.project_id,p.name project_name,pm.role status,pm.joined_at updated_at,pm.project_id target_id FROM project_members mine JOIN project_members pm ON pm.project_id=mine.project_id JOIN projects p ON p.id=pm.project_id JOIN users u ON u.id=pm.user_id WHERE mine.user_id=? AND (? IS NULL OR pm.project_id=?) AND (LOWER(u.display_name) LIKE ? ESCAPE '!' OR LOWER(u.email_normalized) LIKE ? ESCAPE '!')"+(c!=null||nonblank(status)?" AND 1=0":"");return new Branch(sql,Arrays.asList(u.toString(),v(p),v(p),like,like));}
    private Branch attachments(UUID u,UUID p,UUID c,String status,String like){String sql="SELECT 'ATTACHMENT' entity_type,a.id,a.original_filename title,a.media_type snippet,r.project_id,p.name project_name,r.status,a.created_at updated_at,r.id target_id FROM attachments a JOIN experiment_records r ON r.id=a.record_id JOIN projects p ON p.id=r.project_id JOIN project_members pm ON pm.project_id=r.project_id WHERE pm.user_id=? AND a.deleted_at IS NULL AND r.deleted_at IS NULL AND r.provisional=FALSE AND (? IS NULL OR r.project_id=?) AND (? IS NULL OR r.creator_id=?) AND (? IS NULL OR r.status=?) AND (LOWER(a.original_filename) LIKE ? ESCAPE '!' OR LOWER(a.media_type) LIKE ? ESCAPE '!')";String st=nonblank(status)?status:null;return new Branch(sql,Arrays.asList(u.toString(),v(p),v(p),v(c),v(c),st,st,like,like));}
    private String escape(String v){return v.replace("!","!!").replace("%","!%").replace("_","!_");}private boolean nonblank(String v){return v!=null&&!v.isBlank();}private String v(UUID id){return id==null?null:id.toString();}private record Branch(String sql,List<Object>args){}
}
