import { useEffect, useState } from 'react'
import { Send } from 'lucide-react'
import { Button } from '@/components/ui'
import { fetchReviewerCandidates, submitRecord } from '@/api'

export default function SubmissionDialog({ record, open, onClose, onSubmitted }) {
  const [candidates, setCandidates] = useState([]), [reviewerId, setReviewerId] = useState(''), [note, setNote] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  useEffect(() => { if (!open) return; setError(''); fetchReviewerCandidates(record.id).then((value) => { setCandidates(value); setReviewerId(value[0]?.userId || '') }).catch((e) => setError(e.message)) }, [open, record.id])
  if (!open) return null
  const submit = async () => { setLoading(true); setError(''); try { const revision = await submitRecord(record.id, { reviewerId, submitNote: note, expectedRecordVersion: record.version }); onSubmitted(revision) } catch (e) { setError(e.message) } finally { setLoading(false) } }
  return <div role="dialog" aria-label="提交审核" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-lg font-semibold">提交审核并生成 R{record.currentRevisionNo + 1}</h2><p className="mt-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">提交后不可撤回；正文、模板字段和当前附件将形成不可变快照并锁定。</p>{error && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="field-label mt-4">指定审核人 *</label><select aria-label="指定审核人" className="input" value={reviewerId} onChange={(e) => setReviewerId(e.target.value)}><option value="">请选择</option>{candidates.map((candidate) => <option key={candidate.userId} value={candidate.userId}>{candidate.displayName}（{candidate.role === 'OWNER' ? '负责人' : '审核者'}）</option>)}</select>{candidates.length === 0 && !error && <p className="mt-2 text-sm text-amber-700">暂无合法审核人，请联系项目负责人添加审核者或调整角色。</p>}<label className="field-label mt-4">提交说明</label><textarea aria-label="提交说明" className="input min-h-24" maxLength={2000} value={note} onChange={(e) => setNote(e.target.value)} /><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={onClose} disabled={loading}>取消</Button><Button icon={Send} loading={loading} disabled={!reviewerId || candidates.length === 0} onClick={submit}>确认提交</Button></div></div></div>
}
